<a href="https://colab.research.google.com/github/sharminema05/Assignment/blob/main/SIM_Lab_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
# Generating a 3×3 matrix of random integers between 1 and 50
matrix = np.random.randint(1, 50, (3, 3))
print("Random Matrix:\n",matrix,"\n")

Random Matrix:
 [[37 48 12]
 [25 44 34]
 [ 9 37 15]] 



In [11]:
# Generating a 3×3 matrix of random integers between 1 and 50
matrix = np.random.randint(1, 50, (3, 3))
print("Random Matrix:\n",matrix,"\n")

# With fixed seed
np.random.seed(10)
matrix_fixed_seed = np.random.randint(1, 51, (3, 3))

# Without fixed seed
matrix_without_fixed_seed = np.random.randint(1, 51, (3, 3))
print("Matrix setting fixed seed:\n",matrix_fixed_seed)
print("\nMatrix without fixed seed:\n",matrix_without_fixed_seed)

# With Fixed Seed: The numbers stay the same every time you run the code because the seed locks the random order.
# Without Fixed Seed: The numbers change each time you run the code because there is no set starting point.


Random Matrix:
 [[14  6 14]
 [26 14 29]
 [23 31 31]] 

Matrix setting fixed seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without fixed seed:
 [[30 50  9]
 [10  1 43]
 [41 37 17]]
